# Generated by Django 4.2.11 on 2024-12-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=40)),
                ('weigth', models.DecimalField(decimal_places=5, max_digits=10)),
                ('heigth', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
