# Generated by Django 4.2 on 2025-01-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_pokemon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='trainer_images/'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('E', 'Electrico'), ('C', 'Tierra'), ('F', 'Lagartija'), ('A', 'Agua'), ('D', 'Planta'), ('B', 'Fuego')], max_length=30),
        ),
    ]
